### PR TITLE
Implemented library linking

### PR DESCRIPTION
**Pull request by Antanukas**

### CODE REVIEW

**Comment by uzyn** [comment]
@Antanukas Thanks. Can you link to a solidity code that we could test this new feature?

**Comment by Antanukas** [comment]
https://github.com/Antanukas/ethereum-webpack-example-dapp

**Comment by graup** [comment]
Cool, thanks! Works for me.
@uzyn please check it out and merge!

**Comment by uzyn** [comment]
@Antanukas and @graup 
Yup works for me too. 

Sorry, I was traveling quite a bit the last 2 weeks. 

Thanks.

**Pull request merged**
